apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:  
  name: quay-enterprise-config-tool-role
  namespace: quay-enterprise
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - put
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - "extensions"
  - "apps"
  resources:
  - deployments
  - deployments/rollback
  verbs:
  - create
  - get
  - list
  - patch
