apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: quay-enterprise
  name: quay-enterprise-config-tool
  labels:
    quay-enterprise-component: config-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-enterprise-component: config-tool
  template:
    metadata:
      namespace: quay-enterprise
      labels:
        quay-enterprise-component: config-tool
    spec:
      serviceAccountName: qe-config-tool-serviceaccount
      volumes:
        - name: configvolume
          secret:
            secretName: quay-enterprise-config-secret
      containers:
      - name: quay-enterprise-config-tool
        image: config-app:latest # TODO: change to reference to quay image?
        imagePullPolicy: IfNotPresent # enable when testing with minikube
        args: ["config"]
        ports:
        - containerPort: 80
