---
apiVersion: v1
kind: Template
metadata:
  name: ${{NAME}}
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${{NAME}}
  spec:
    type: LoadBalancer
    ports:
    - name: prometheus-proxy-loadbalancer
      protocol: TCP
      port: 3000
      targetPort: 3000
    selector:
      app: prometheus
parameters:
  - name: NAME
    value: prometheus-loadbalancer-service
    displayName: name
    description: Defaults to prometheus-loadbalancer-service
